services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - '5432:5432'
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
